# Generated by Django 4.0.1 on 2022-04-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_movie_cast_movie_director_movie_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=150)),
                ('bookformat', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=150)),
                ('pages', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
